### PR TITLE
dev-lang/rust: fix manifests and disable src-tarball generation

### PR DESCRIPTION
**Pull request by stefson**
No idea what fffb8f3 is doing here..

### CODE REVIEW

**Comment by stefson** [comment]
Seems I just learned how to sync a fork :) if this is conflicting with the master branch please let me know and I'll open another pull request with a clean fork.

**Comment by smaeul** [comment]
@stefson I went ahead and rebased this

**Comment by stefson** [comment]
You disagree about the rest?

**Comment by smaeul** [comment]
No, I just ran into an issue when creating the arm stage0 that I haven't had a chance to work through (LLVM, libstdc++, and float ABI nonsense, not actually an issue with rust)

**Pull request closed without merging**
